// Generated by Cypress Author — 2026-05-25
import { defaultDbSeed, DBSeed, getSpriteFromCels } from '../support/data';
import { rgba } from '../support/utils';

const T = rgba(0, 0, 0, 0);
const RED = rgba(255, 0, 0);
const GREEN = rgba(0, 128, 0);
const BLACK = rgba(0, 0, 0);

const twoFramesTwoLayersSeed: DBSeed = {
  ...defaultDbSeed,
  sprite: getSpriteFromCels(
    [
      [[[RED, T], [T, T]], [[T, T], [T, RED]]],   // frame-0: layer-0 red(0,0) | layer-1 red(1,1)
      [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]], // frame-1: layer-0 green(1,1) | layer-1 empty
    ],
    [{ duration: 150 }, { duration: 100 }],
    [
      { 'visible?': true, 'automatic-linking?': false, name: 'Layer 1' },
      { 'visible?': true, 'automatic-linking?': false, name: 'Layer 2' }
    ]
  )
};

describe('Timeline', () => {
  describe('Display', () => {
    it('frame numbers, layer names, cel previews, and canvas match selected cel', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],
      ], { activeFrameIdx: 0, activeLayerIdx: 0 }, ['Layer 1', 'Layer 2']);

      cy.get('[data-testid="input-frame-duration"]').should('have.value', '150', 'frame-0 duration is 150');
      cy.get('[data-testid="cel-1-1"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],
      ], { activeFrameIdx: 1, activeLayerIdx: 1 }, ['Layer 1', 'Layer 2']);
      cy.get('[data-testid="input-frame-duration"]').should('have.value', '100', 'frame-1 duration is 100');
    });
  });

  describe('Frames', () => {
    it('remove frame → previous frame becomes active and canvas updates', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      // Move to frame-1
      cy.get('[data-testid="cel-1-0"]').click();
      cy.get('[data-testid="frame-1"][data-current="true"]').should('exist', 'frame-1 is active before remove');
      cy.get('[title="remove frame"]').click();

      // Only frame-0 remains, previous frame is selected
      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],
      ], { activeFrameIdx: 0, activeLayerIdx: 0 }, ['Layer 1', 'Layer 2']);
      cy.get('[title="remove frame"]').should('be.disabled', 'remove frame button is disabled when only one frame exists');
    });

    it('duplicate frame → copy inserted after current, new frame becomes active', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[title="duplicate frame"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],           // frame-0: unchanged
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],           // frame-1: duplicate of frame-0 (active)
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],     // frame-2: was frame-1
      ], { activeFrameIdx: 1, activeLayerIdx: 0 }, ['Layer 1', 'Layer 2']);
    });

    it('move frame right → frame moves to next position, button disabled on last frame', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid="cel-0-1"]').click();
      cy.get('[title="move frame right"]').should('not.be.disabled', 'button enabled when not on last frame');

      cy.get('[title="move frame right"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],   // frame-0: was frame-1
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],       // frame-1: was frame-0 (active)
      ], { activeFrameIdx: 1, activeLayerIdx: 1 }, ['Layer 1', 'Layer 2']);

      cy.get('[title="move frame right"]').should('be.disabled', 'button disabled on last frame');
    });

    it('move frame left → frame moves to previous position, button disabled on first frame', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid="cel-1-1"]').click();
      cy.get('[title="move frame left"]').should('not.be.disabled', 'button enabled when not on first frame');

      cy.get('[title="move frame left"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],   // frame-0: was frame-1 (active)
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],       // frame-1: was frame-0
      ], { activeFrameIdx: 0, activeLayerIdx: 1 }, ['Layer 1', 'Layer 2']);

      cy.get('[title="move frame left"]').should('be.disabled', 'button disabled on first frame');
    });

    it('add empty frame → new frame is active, is empty, draw works', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[title="add empty frame"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],   // frame-0: layer-0 red | layer-1 red(1,1)
        [[[T, T], [T, T]], [[T, T], [T, T]]],       // frame-1 (new, active): empty | empty
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]], // frame-2 (was frame-1): layer-0 green | layer-1 empty
      ], { activeFrameIdx: 1, activeLayerIdx: 0 }, ['Layer 1', 'Layer 2']);

      cy.selectTool('pen');
      cy.drawAtCanvasPixel(0, 0);
      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, RED]]],   // frame-0: unchanged
        [[[BLACK, T], [T, T]], [[T, T], [T, T]]],   // frame-1: black pixel drawn
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]], // frame-2: unchanged
      ], { activeFrameIdx: 1, activeLayerIdx: 0 }, ['Layer 1', 'Layer 2']);
    });
  });

  describe('Layers', () => {
    it('add layer → new layer inserted after current, becomes active', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[title="add layer"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, T]], [[T, T], [T, RED]]],      // frame-0: L1 | new empty (active) | L2
        [[[T, T], [T, GREEN]], [[T, T], [T, T]], [[GREEN, T], [T, T]]],  // frame-1: L1 | new empty | L2
      ], { activeFrameIdx: 0, activeLayerIdx: 1 }, ['Layer 1', 'Layer 3', 'Layer 2']);
    });

    it('remove layer → layer removed, previous selected, button disabled with single layer', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid="cel-0-1"]').click();
      cy.get('[data-testid="btn-remove-layer"]').should('not.be.disabled', 'button enabled with multiple layers');

      cy.get('[data-testid="btn-remove-layer"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]]],        // frame-0: only Layer 1 remains (active)
        [[[T, T], [T, GREEN]]],      // frame-1: only Layer 1 remains
      ], { activeFrameIdx: 0, activeLayerIdx: 0 }, ['Layer 1']);

      cy.get('[data-testid="btn-remove-layer"]').should('be.disabled', 'button disabled with single layer');
    });

    it('merge layer with below → pixels merged into current layer, below removed', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid="cel-0-1"]').click();
      cy.get('[data-testid="btn-merge-layer-with-below"]').should('be.disabled', 'disabled on last layer');

      cy.get('[data-testid="cel-0-0"]').click();
      cy.get('[data-testid="btn-merge-layer-with-below"]').should('not.be.disabled', 'enabled when layer below exists');

      cy.get('[data-testid="btn-merge-layer-with-below"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, RED]]],      // frame-0: merged layer (active)
        [[[GREEN, T], [T, GREEN]]], // frame-1: merged layer
      ], { activeFrameIdx: 0, activeLayerIdx: 0 }, ['Layer 1']);

      cy.get('[data-testid="btn-merge-layer-with-below"]').should('be.disabled', 'disabled with single layer');
    });

    it('move layer up → layer moves to previous position, button disabled on first layer', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid="cel-0-0"]').click();
      cy.get('[data-testid="btn-move-layer-up"]').should('be.disabled', 'disabled on first layer');

      cy.get('[data-testid="cel-0-1"]').click();
      cy.get('[data-testid="btn-move-layer-up"]').should('not.be.disabled', 'enabled when not first layer');

      cy.get('[data-testid="btn-move-layer-up"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[T, T], [T, RED]], [[RED, T], [T, T]]],      // frame-0: L2 (active) | L1
        [[[GREEN, T], [T, T]], [[T, T], [T, GREEN]]],  // frame-1: L2 | L1
      ], { activeFrameIdx: 0, activeLayerIdx: 0 }, ['Layer 2', 'Layer 1']);

      cy.get('[data-testid="btn-move-layer-up"]').should('be.disabled', 'disabled on first layer after move');
    });

    it('move layer down → layer moves to next position, button disabled on last layer', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid="cel-0-1"]').click();
      cy.get('[data-testid="btn-move-layer-down"]').should('be.disabled', 'disabled on last layer');

      cy.get('[data-testid="cel-0-0"]').click();
      cy.get('[data-testid="btn-move-layer-down"]').should('not.be.disabled', 'enabled when not last layer');

      cy.get('[data-testid="btn-move-layer-down"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[T, T], [T, RED]], [[RED, T], [T, T]]],      // frame-0: L2 | L1 (active)
        [[[GREEN, T], [T, T]], [[T, T], [T, GREEN]]],  // frame-1: L2 | L1
      ], { activeFrameIdx: 0, activeLayerIdx: 1 }, ['Layer 2', 'Layer 1']);

      cy.get('[data-testid="btn-move-layer-down"]').should('be.disabled', 'disabled on last layer after move');
    });

    it('rename layer → layer name updates in timeline', () => {
      cy.startApp(twoFramesTwoLayersSeed);
      cy.stubPrompt('Background');

      cy.get('[data-testid="btn-rename-layer"]').click();

      cy.assertTimelineLabels(2, ['Background', 'Layer 2']);
    });

    it('rename layer cancel → layer name unchanged', () => {
      cy.startApp(twoFramesTwoLayersSeed);
      cy.stubPrompt(null);

      cy.get('[data-testid="btn-rename-layer"]').click();

      cy.assertTimelineLabels(2, ['Layer 1', 'Layer 2']);
    });

    it('duplicate layer → copy inserted after current with same pixels, becomes active', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid="btn-duplicate-layer"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[RED, T], [T, T]], [[T, T], [T, RED]]],      // frame-0: L1 | dup (active) | L2
        [[[T, T], [T, GREEN]], [[T, T], [T, GREEN]], [[GREEN, T], [T, T]]], // frame-1: L1 | dup | L2
      ], { activeFrameIdx: 0, activeLayerIdx: 1 }, ['Layer 1', 'Layer 1', 'Layer 2']);
    });
  });
});
