// Generated by Cypress Author — 2026-05-25
import { defaultDbSeed, DBSeed, getSpriteFromCels } from '../support/data';
import { rgba } from '../support/utils';

const T = rgba(0, 0, 0, 0);
const RED = rgba(255, 0, 0);
const GREEN = rgba(0, 128, 0);
const BLACK = rgba(0, 0, 0);

const twoFramesTwoLayersSeed: DBSeed = {
  ...defaultDbSeed,
  sprite: getSpriteFromCels(
    [
      [[[RED, T], [T, T]], [[T, T], [T, T]]],   // frame-0: layer-0 red(0,0) | layer-1 empty
      [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]], // frame-1: layer-0 green(1,1) | layer-1 empty
    ],
    [{ duration: 150 }, { duration: 100 }],
    [
      { 'visible?': true, 'automatic-linking?': false, name: 'Layer 1' },
      { 'visible?': true, 'automatic-linking?': false, name: 'Layer 2' }
    ]
  )
};

describe('Timeline', () => {
  describe('Display', () => {
    it('frame numbers, layer names, cel previews, and canvas match selected cel', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.assertTimelineLabels(2, ['Layer 1', 'Layer 2']);
      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, T]]],
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],
      ], { activeFrameIdx: 0, activeLayerIdx: 0 });

      cy.get('[data-testid="input-frame-duration"]').should('have.value', '150', 'frame-0 duration is 150');
      cy.get('[data-testid="cel-1-1"]').click();

      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, T]]],
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],
      ], { activeFrameIdx: 1, activeLayerIdx: 1 });
      cy.get('[data-testid="input-frame-duration"]').should('have.value', '100', 'frame-1 duration is 100');
    });
  });

  describe('Frames', () => {
    it('remove frame → previous frame becomes active and canvas updates', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      // Move to frame-1
      cy.get('[data-testid="cel-1-0"]').click();
      cy.get('[data-testid="frame-1"][data-current="true"]').should('exist', 'frame-1 is active before remove');
      cy.get('[title="remove frame"]').click();

      // Only frame-0 remains, previous frame is selected
      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, T]]],
      ], { activeFrameIdx: 0, activeLayerIdx: 0 });
      cy.assertTimelineLabels(1, ['Layer 1', 'Layer 2']);
      cy.get('[title="remove frame"]').should('be.disabled', 'remove frame button is disabled when only one frame exists');
    });

    it('duplicate frame → copy inserted after current, new frame becomes active', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[title="duplicate frame"]').click();

      cy.assertTimelineLabels(3, ['Layer 1', 'Layer 2']);
      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, T]]],           // frame-0: unchanged
        [[[RED, T], [T, T]], [[T, T], [T, T]]],           // frame-1: duplicate of frame-0 (active)
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]],     // frame-2: was frame-1
      ], { activeFrameIdx: 1, activeLayerIdx: 0 });
    });

    it('add empty frame → new frame is active, is empty, draw works', () => {
      cy.startApp(twoFramesTwoLayersSeed);

      cy.get('[data-testid^="frame-"]').should('have.length', 2);

      cy.get('[title="add empty frame"]').click();

      cy.assertTimelineLabels(3, ['Layer 1', 'Layer 2']);
      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, T]]],   // frame-0: layer-0 red | layer-1 empty
        [[[T, T], [T, T]], [[T, T], [T, T]]],     // frame-1 (new, active): empty | empty
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]], // frame-2 (was frame-1): layer-0 green | layer-1 empty
      ], { activeFrameIdx: 1, activeLayerIdx: 0 });

      cy.selectTool('pen');
      cy.drawAtCanvasPixel(0, 0);
      cy.assertTimelineCelsAndVisiblePixels([
        [[[RED, T], [T, T]], [[T, T], [T, T]]],   // frame-0: layer-0 red | layer-1 empty
        [[[BLACK, T], [T, T]], [[T, T], [T, T]]],     // frame-1 (new, active): empty | empty
        [[[T, T], [T, GREEN]], [[GREEN, T], [T, T]]], // frame-2 (was frame-1): layer-0 green | layer-1 empty
      ], { activeFrameIdx: 1, activeLayerIdx: 0 });
    });
  });
});
